apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-Pod
spec:
  containers:
  - name: secrets-demo-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom: 
        secretKeyRef:
          name: my-secret
          key: username
  - name: SECRET_PASSWORD
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: password
    volumeMounts:
    - name: secret-volume
      mountPath: "etc/secrets-volume"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret